spring:
  profiles:
    active: dev
    group:
      dev:
        - common
        - dev
      prod:
        - common
        - prod

---

spring:
  config:
    activate:
      on-profile: common
  threads:
    virtual:
      enabled: true
  datasource:
    #url: jdbc:mysql://localhost:13306/ulala_main?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: admin
    password: admin

  jpa:
    open-in-view: false
  sql:
    init:
      schema-locations: classpath:ddl.sql
      data-locations: classpath:dml.sql

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: spring.sample

---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080

