spring:
  profiles:
    active: dev
    group:
      dev:
        - common
        - dev
      prod:
        - common
        - prod

---

spring:
  config:
    activate:
      on-profile: common
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:13306/ulala_main?allowPublicKeyRetrieval=true&useSSL=false
    username: ulala
    password: ula123$
  jpa:
    open-in-view: false

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: spring.sample

---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080

