spring:
  profiles:
    active: dev
    group:
      dev:
        - common
        - dev
      prod:
        - common
        - prod

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/echobase
    username: czhang
    password: chzh123$

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: com.ulala

---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080

