spring:
  profiles:
    active: dev
    group:
      dev:
        - common
        - dev
      prod:
        - common
        - prod

---

spring:
  config:
    activate:
      on-profile: common
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/echobase?allowPublicKeyRetrieval=true&useSSL=false
    username: czhang
    password: chzh123$

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: com.ulala

---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080

